### ISSUE TITLE
Maven Central

### ISSUE THREAD

**Issue by j-ibarra** [Fewlaps/slim-jpg#10]
Hello, thank you very much for the contribution, it would be good to be published in central maen

**Comment by rocboronat** [comment]
Hello! Publishing to Maven Central is not that easy. Is there any reason to avoid using jcenter?

**Comment by cyberquarks** [comment]
@rocboronat JCenter is now deprecated

**Comment by rocboronat** [comment]
Haha! Yes! I have to do some chores 😊

**Comment by ZoidbergVA** [comment]
@rocboronat Any news on when this will be available on a new maven repository?

**Comment by rocboronat** [comment]
Not yet 😄 But Jcenter will keep the library so the only worry is for the updates. I have too much OS libraries and I prioritize Barista, the most widely used one 😊
